apiVersion: v1
kind: Service
metadata:
  name: myapp-cip-service
  labels:
    app: myapp
    env: dev
    tier: back-end
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
