apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: httpd
      labels:
        app: frontend
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine