apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myapp-custom-sc
  labels:
    app: myapp
    env: dev
    tier: back-end
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-balanced
