apiVersion: v1
kind: Service
metadata:
  name: myapp-headless-service
  labels:
    app: myapp
    env: dev
    tier: back-end
spec:
  clusterIP: None
  selector:
    tier: back-end
  ports:
  - port: 80 # both the "Service Port and Target Port" must be same
    targetPort: 80
