apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    env: dev
    tier: front-end
spec:
  selector:
    matchLabels:
      tier: front-end
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        tier: front-end
    spec:
      containers:
        - name: nginx-container-2
          image: nginx
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
