apiVersion: v1
kind: Service
metadata:
  name: myapp-np-service
  labels:
    app: myapp
    env: dev
    tier: front-end
spec:
  selector:
    tier: front-end
  type: NodePort
  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
