apiVersion: v1
kind: Service
metadata:
  name: eapp-flask-lb-service
  labels:
    app: eapp-flask
    env: dev
    tier: front-end
    project: goto-codes
spec:
  type: LoadBalancer
  selector:
    app: eapp-flask
    tier: front-end
  ports:
  - port: 80
    targetPort: 4999
